theme = "void_transparent"

[editor]
line-number = "relative"
bufferline = "always"
cursorline = true
color-modes = true
auto-format = true
idle-timeout = 500
# completion-trigger-len = 1
gutters = ["diagnostics", "spacer", "line-numbers", "spacer", "diff"]

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.lsp]
display-messages = true
display-inlay-hints = true

[editor.indent-guides]
render = true
character = "|"
skip-levels = 1

[editor.whitespace.render]
space = "none"
tab = "all"
newline = "none"

[editor.whitespace.characters]
tab = "→"
tabpad = "·"

[editor.statusline]
left = ["mode", "spacer", "spinner", "file-name", "file-modification-indicator"]
center = []
right = ["diagnostics", "selections", "position", "file-encoding", "file-type"]
separator = "|"
mode.normal = "NORMAL"
mode.insert = "INSERT"
mode.select = "SELECT"

[keys.normal]
"tab" = "goto_next_buffer"
"S-tab" = "goto_previous_buffer"
"A-q" = ":buffer-close"

[keys.normal.space]
"/" = "file_explorer_in_current_buffer_directory"
"E" = "file_picker"
"e" = "file_picker_in_current_buffer_directory"
"f" = "global_search"
"F" = "file_explorer"
