#!/usr/bin/env bash

FACE="$HOME/voidbloom13-dotfiles/assets/profile.jpg"
WALLPAPER="$HOME/voidbloom13-dotfiles/assets/fedora-wallpaper.jpg"

function gnome_install {
    sudo dnf install -y \
        gnome-tweaks \
        gnome-extensions-app
    flatpak install GdmSettings
}

function kde_install {
    echo "Running from KDE Plasma"
}

function gui_install {
    sudo dnf install -y \
        google-chrome-stable \
        kitty

    # Installs Nerd Fonts
    git clone --depth 1 https://github.com/ryanoasis/nerd-fonts ~/Downloads/nerd-fonts
    ./$HOME/Downloads/nerd-fonts/install.sh
    sudo fc-cache -fv
}

function initial_install {
    # Base Packages
    sudo dnf install -y \
        bat \
        dnf-plugins-core \
        fastfetch \
        flatpak \
        fzf \
        gcc \
        git \
        gh \
        man-pages \
        nvim \
        ripgrep \
        rsync \
        stow \
        tailscale \
        tmux \
        tree \
        unzip \
        zip \
        zoxide \
        zsh

    # Docker
    sudo dnf remove -y \
        docker \
        docker-client \
        docker-client-latest \
        docker-common \
        docker-latest \
        docker-latest-logrotate \
        docker-logrotate \
        docker-selinux \
        docker-engine-selinux \
        docker-engine
    sudo dnf config-manager addrepo --from-repofile https://download.docker.com/linux/fedora/docker-ce.repo
    sudo dnf install -y \
        docker-ce \
        docker-ce-cli \
        containerd.io \
        docker-buildx-plugin \
        docker-compose-plugin

    # Languages
    sudo dnf install -y \
        dotnet-sdk-10.0 \
        java-latest-openjdk \
        maven \
        nodejs \
        postgresql-server \
        postgresql-contrib \
        python3.12 \
        python3.12-pip \

        # SDKMAN and Springboot CLI
    curl -s "https://get.sdkman.io" | bash
    source "$HOME/.sdkman/bin/sdkman-init.sh"
    sdk install springboot

    # TMUX Theme and TPM
    mkdir -p ~/.config/tmux/plugins/catppuccin
    git clone https://github.com/tmux-plugins/tpm ~/.tmux/plugins/tpm
    git clone -b v2.1.3 https://github.com/catppuccin/tmux.git ~/.config/tmux/plugins/catppuccin/tmux

    # NVM and NodeJS LTS
    curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.40.4/install.sh | bash
    export NVM_DIR="$HOME/.nvm"
    [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
    [ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"
    nvm install --lts && nvm use --lts

    # NPM Installs
    sudo npm install -g \
        @angular/cli \
        @angular/language-server \
        @google/gemini-cli \
        nodemon \
        prettier-plugin-tailwindcss \
        typescript \
        typescript-language-server \
        @tailwindcss/language-server

    # PSQL
    sudo postgresql-setup --initdb --unit postgresql

    # Systemd Services
    sudo systemctl enable --now docker
    sudo usermod -aG docker $USER
    sudo systemctl enable --now postgresql
    sudo systemctl enable --now tailscaled
}

# function create_symlinks {
#     local dotfiles_dir="$HOME/.dotfiles"
#     local dotfiles_target="$HOME"
#
#     # 1. Top-level items in $dotfiles_dir
#     find "$dotfiles_dir" -mindepth 1 -maxdepth 1 | while IFS= read -r item; do
#         name=$(basename "$item")
#         [[ "$name" == ".git" ]] && continue
#
#         if [[ -f "$item" ]]; then
#             rel="${item#$dotfiles_dir/}"
#             dest="$dotfiles_target/$rel"
#             if [[ -e "$dest" && ! -L "$dest" ]]; then
#                 echo "Backing up $dest -> ${dest}.bak"
#                 mv "$dest" "${dest}.bak"
#             fi
#         fi
#
#         if [[ -d "$item" ]]; then
#             # 2. One level deeper for subdirs (e.g. .config/nvim)
#             find "$item" -mindepth 1 -maxdepth 1 | while IFS= read -r sub; do
#                 rel="${sub#$dotfiles_dir/}"
#                 dest="$dotfiles_target/$rel"
#                 if [[ -e "$dest" && ! -L "$dest" ]]; then
#                     echo "Backing up $dest -> ${dest}.bak"
#                     mv "$dest" "${dest}.bak"
#                 fi
#             done
#         fi
#     done
#     echo "Running stow..."
#     stow -v -t "$dotfiles_target" -d "$dotfiles_dir" .
# }
#
# function dotfiles_setup {
#     local dotfiles_repo="https://github.com/voidbloom13/arch-dotfiles"
#     local dotfiles_dir="$HOME/.dotfiles"
#     local temp_dir="$HOME/repo_dotfiles"
#
#     echo -e "\e[1;44;87m             Import dotfiles?             \e[0m"
#     read -p "Would you like to sync dotfiles? [Y/n] " dotfiles_setup
#     dotfiles_setup=${dotfiles_setup:-Y}
#     case $dotfiles_setup in
#         [yY] )
#             echo "Importing dotfiles now..."
#             mkdir -p $dotfiles_dir
#             git clone $dotfiles_repo $temp_dir
#             rsync -av --backup --backup-dir="$dotfiles_dir/.backups" --suffix=".bak" $temp_dir/.dotfiles/ $dotfiles_dir
#             rm -rf $temp_dir
#             echo "Import complete."
#             create_symlinks
#             ;;
#         [nN] )
#             echo "Skipping dotfiles import."
#             ;;
#         * )
#             echo "Skipping dotfiles import."
#             ;;
#     esac
# }

function git_setup {
    echo -e "\e[1;44;87m             Git and Github Setup             \e[0m"
    read -p "Setup git/github? [Y/n] " setup_git
    setup_git=${setup_git:-Y}
    case $setup_git in
        [yY] )
            read -p "Git config name: " git_name
            read -p "Git config email: " git_email
            git config --global user.name "$git_name" && git config --global user.email "$git_email"
            gh auth login
            ;;
        [nN] )
            echo "Exiting git setup..."
            ;;
        * )
            echo "Exiting git setup..."
            ;;
    esac
}

function main {
    sudo dnf update -y
    initial_install
    git_setup
    # dotfiles_setup

    find "$HOME/voidbloom13-dotfiles/.dotfiles/" -mindepth 1 -maxdepth 1 -type d | while read -r package; do
        bash $HOME/voidbloom13-dotfiles/scripts/stow $(basename "$package")
    done

    ln -s voidbloom13-dotfiles/.prettierrc.json $HOME/.prettierrc.json
    if ! uname -a | grep WSL && pgrep -l "Xorg|wayland"; then
        gui_install
    fi

    case "$XDG_CURRENT_DESKTOP" in
        *GNOME*)
            gnome_install
            gsettings set org.gnome.desktop.background picture-uri "file://$WALLPAPER"
            gsettings set org.gnome.desktop.background picture-uri-dark "file://$WALLPAPER"
            ln -s $FACE ~/.face
            chmod 644 ~/.face
            ;;
        *KDE*)
            kde_install
            plasma-apply-wallpaperimage "$WALLPAPER"
            ln -s $FACE ~/.face
            chmod 644 ~/.face
            ;;
        *)
            echo "$XDG_CURRENT_DESKTOP not supported. Please ensure settings are configured manually."
            ;;
    esac

    . ~/.profile && . ~/.bashrc
    clear && fastfetch
    echo -e "\e[1;37mNext Steps\e[0m:"
    echo -e "* Run \e[1;33m[sudo tailscale up]\e[0m and follow the link to set up \e[1;33mTailscale VPN\e[0m"
    echo -e "* Run \e[1;35m[chsh]\e[0m and change user shell to \e[1;35m/usr/bin/zsh\e[0m"
    echo -e "* Run \e[1;32m[tmux]\e[0m and press \e[1;32m[<ctrl>+b, I]\e[0m to install tmux plugins"
    echo -e "* Run \e[1;34m:MasonInstallAll\e[0m inside \e[1;34mNeovim\e[0m"
}

main
