#!/usr/bin/env bash

FACE="$HOME/voidbloom13-dotfiles/assets/profile.jpg"
WALLPAPER="$HOME/voidbloom13-dotfiles/assets/arch-wallpaper.jpg"
TERM_WALLPAPER="$HOME/voidbloom13-dotfiles/assets/terminal-wallpaper.jpg"

function main {
    # System Update + Base Packages
    sudo pacman -Syu \
        base-devel \
        bat \
        cifs-utils \
        curl \
        fastfetch \
        flatpak \
        fzf \
        gcc \
        git \
        github-cli \
        man-db \
        neovim \
        ripgrep \
        rsync \
        stow \
        tailscale \
        tmux \
        tree \
        unzip \
        zip \
        zoxide \
        zsh

    # Docker
    sudo pacman -Syu \
        docker

    # Languages
    sudo pacman -Syu \
        aspnet-runtime \
        dotnet-runtime \
        dotnet-sdk \
        jdk-openjdk \
        maven \
        nodejs \
        npm \
        pgcli \
        postgresql \
        python \
        python-pip

    # Yay AUR Helper
    git clone https://aur.archlinux.org/yay
    cd yay
    makepkg -si
    cd $HOME

    # Claude Code
    curl -fsSL https://claude.ai/install.sh | bash

    # NVM and NodeJS LTS
    curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.40.4/install.sh | bash
    export NVM_DIR="$HOME/.nvm"
    [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
    [ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"
    nvm install --lts && nvm use --lts

    # SDKMAN and Spring CLI
    curl -s "https://get.sdkman.io" | bash
    source $HOME/.sdkman/bin/sdkman-init.sh
    sdk install springboot

    # TMUX Theme and TPM
    mkdir -p ~/.config/tmux/plugins/catppuccin
    git clone https://github.com/tmux-plugins/tpm ~/.tmux/plugins/tpm
    git clone -b v2.1.3 https://github.com/catppuccin/tmux.git ~/.config/tmux/plugins/catppuccin/tmux

    # NPM Packages
    sudo npm install -g \
        @angular/cli \
        @angular/language-server \
        @google/gemini-cli \
        nodemon \
        prettier-plugin-tailwindcss \
        typescript \
        typescript-language-server \
        @tailwindcss/language-server

    # PostgreSQL Init
    sudo -u postgres initdb -D /var/lib/postgres/data

    # Dotfiles Sync
    find "$HOME/voidbloom13-dotfiles/.dotfiles/" -mindepth 1 -maxdepth 1 -type d | while read -r package; do
        bash $HOME/voidbloom13-dotfiles/scripts/stow $(basename "$package")
    done
    ln -s $HOME/voidbloom13-dotfiles/.prettierrc.json $HOME/.prettierrc.json

    # GUI Apps
    if ! uname -a | grep -q WSL && (pgrep -l "Xorg" || pgrep -l "wayland"); then
        sudo pacman -Syu \
            ghostty \
            kitty \
            ttf-font-awesome \
            $(pacman -Sgq nerd-fonts)

        yay -S google-chrome

        chmod 644 $FACE
        ln -s $FACE ~/.face
        ln -s $TERM_WALLPAPER ~/.config/kitty/wallpaper.jpg
    fi

    # DE-Specific Setup
    case "$XDG_CURRENT_DESKTOP" in
        *GNOME*)
            echo "Setting up Gnome Desktop..."
            sudo pacman -Syu \
                gnome \
                gnome-tweaks \
                extension-manager
            yay -S \
                gdm-settings
            gsettings set org.gnome.desktop.background picture-uri "file://$WALLPAPER"
            gsettings set org.gnome.desktop.background picture-uri-dark "file://$WALLPAPER"
            ;;
        *KDE*)
            echo "Setting up KDE Plasma Desktop..."
            plasma-apply-wallpaperimage "$WALLPAPER"
            ;;
        *)
            echo "$XDG_CURRENT_DESKTOP not supported. Please ensure settings are configured manually."
            ;;
    esac

    # Git and Github Setup
    echo -e "\e[1;44;87m             Git and Github Setup             \e[0m"
    read -p "Setup git/github? [Y/n] " setup_git
    setup_git=${setup_git:-Y}
    case $setup_git in
        [yY] )
            read -p "Git config name: " git_name
            read -p "Git config email: " git_email
            git config --global user.name "$git_name" && git config --global user.email "$git_email"
            gh auth login
            ;;
        [nN] )
            echo "Exiting git setup..."
            ;;
        * )
            echo "Exiting git setup..."
            ;;
    esac

    # Systemd Services
    sudo systemctl enable --now docker
    sudo usermod -aG docker $USER
    sudo systemctl enable --now postgresql
    sudo systemctl enable --now tailscaled

    # Post-Install
    . ~/.profile && . ~/.bashrc
    clear && fastfetch
    echo -e "\e[1;37mNext Steps\e[0m:"
    echo -e "* Run \e[1;33m[sudo tailscale up]\e[0m and follow the link to set up \e[1;33mTailscale VPN\e[0m"
    echo -e "* Run \e[1;35m[chsh]\e[0m and change user shell to \e[1;35m/usr/bin/zsh\e[0m"
    echo -e "* Run \e[1;32m[tmux]\e[0m and press \e[1;32m[<ctrl>+b, i]\e[0m to install tmux plugins"
}

main
